data-path="node2/data"
genesis-file="config/genesis.json"

static-nodes-file="config/static_nodes.json"

permissions-nodes-contract-version=2
permissions-accounts-contract-enabled=true
permissions-accounts-contract-address="0x0000000000000000000000000000000000008888"

#permissions-nodes-contract-enabled=true
#permissions-nodes-contract-address="0x0000000000000000000000000000000000009999"

#permissions-nodes-config-file-enabled=true
#permissions-accounts-config-file-enabled=true

rpc-http-enabled=true
rpc-http-api=["ETH","NET","IBFT","WEB3","ADMIN","PERM"]
rpc-http-host="127.0.0.1"
rpc-http-port="8546"
rpc-http-cors-origins=["all"]

p2p-host="127.0.0.1"
p2p-port="30304"

host-allowlist=["*"]